jpf-nas = ${config_path}

@using jpf-core

# Model classes - override JDK classes
jpf-nas.boot_classpath = ${jpf-nas}/build/jpf-nas-classes.jar

#
jpf-nas.classpath = \
  ${jpf-nas}/build/classes/java/main;\
  ${jpf-nas}/build/classes/java/test;\
  ${jpf-nas}/build/examples;\
  ${jpf-nas}/build/jpf-nas-examples.jar

# Native peers (host JVM) + libs for examples
jpf-nas.native_classpath = \
  ${jpf-nas}/build/jpf-nas.jar;\
  ${jpf-nas}/lib/*.jar

# tell JPF where to find JPF_* native peer classes
jpf-nas.peer_packages = nas.java.net

